export const SET_BRAINTREE_CLIENT = 'SET_BRAINTREE_CLIENT';
export const SET_BRAINTREE_CLIENT_CREATION_PROMISE = 'SET_BRAINTREE_CLIENT_CREATION_PROMISE';
export const SET_BRAINTREE_CLIENT_EXPIRATION_DATE = 'SET_BRAINTREE_CLIENT_EXPIRATION_DATE';
export const SN_BRAINTREE = 'braintree'

export const SET_PAYMENT_METHOD_NONCE = 'SET_PAYMENT_METHOD_NONCE'
