export const SET_BRAINTREE_CLIENT = 'SET_BRAINTREE_CLIENT';
export const SET_BRAINTREE_CLIENT_EXPIRATION_DATE = 'SET_BRAINTREE_CLIENT_EXPIRATION_DATE';
export const SN_BRAINTREE = 'braintree'

export const SET_USERS = 'SET_USERS'
export const ADD_USER = 'SET_USER'
export const SET_PAYMENT_METHOD_NONCE = 'SET_PAYMENT_METHOD_NONCE'
