export const SET_BRAINTREE_CLIENT = 'SET_BRAINTREE_CLIENT';
export const SET_BRAINTREE_CLIENT_CREATION_PROMISE = 'SET_BRAINTREE_CLIENT_CREATION_PROMISE';
export const SET_BRAINTREE_CLIENT_EXPIRATION_DATE = 'SET_BRAINTREE_CLIENT_EXPIRATION_DATE';
export const SN_BRAINTREE = 'braintree'

export const SET_PAYMENT_METHOD_NONCE = 'SET_PAYMENT_METHOD_NONCE'

export const SET_PAYPAL_CHECKOUT_INSTANCE = 'SET_PAYPAL_CHECKOUT_INSTANCE';
export const SET_PAYPAL_SDK_LOAD_PROMISE = 'SET_PAYPAL_SDK_LOAD_PROMISE';
export const SET_IS_PAYPAL_SDK_LOADED = 'SET_IS_PAYPAL_SDK_LOADED';
